# Notes

* The results from our model and the past studies were alike. Especially the direction. When it comes to magnitude we see differences. This is expected from the fact that the models used in the studies are fundamentally different. Along with that, the costs used in both the models are different as well. As in Variable Costs (VC) vs Variable Costs + Fixed Costs (VC + FC). I could include the fixed costs in the model but it's just an accounting exercise. I do not see the point of it in the model. Here with the different adoption rates simulation, if I remove the VC from the model the change in producer surplus would be zero. Where, in the past studies it would still be negative.  

* The sectors invovled in the model are different as well. I differentiate the type of meat fed cattle vs cull cows. And the prices of those type of cattle.

<!-- * We could consider 20% traceability as a voluntary expansion in traceability participation by some U.S. producers. (This is from Pendall et. al. 2011) -->

* We need to write the differences in the analysis as well. Like how our work depands on different types of data and such.

* Note that the model is mimicking the previous literature indicating the model can be used for policy analysis. We fill the gap in the literature by analysing different types of meat (in our case fed cattle and cull cow) in the model. Specifically, our model is used to study the welfare of producers.

* Increased costs raise cattle and beef prices at each level.


* About adding to literature:
We add to the existing literature of impacts of traceability on producers by using a dynamic model for the analysis. In contrast to the existing literature on the subject, we take a data driven approach to estimate the impacts. Our study fills the gap by analysing different types of cattle, use 


<!-- 
###########################################################################
                                NEW UPDATE
###########################################################################
-->
* I see changes in the priuce and quantities with the increase in demand. When simulating the model with increase in demand we increase the demand for meat before determining the prices i.e., increase the variable A in the code (for instance with a 10 percent increase in demand increase A from demand to demand * (1.1)).
* Upon increasing trhe demand I see the price for fed cattle increased and supply went down drastically. However, the price of cull cows went down and the supply for cull cow meat increased. Just with a 10 percentr increase I see the loss in producer surplus decrease. 
* Need to do more detailed analysis. But I guess this is good news.





