---
output:
  pdf_document: default
  html_document: default
---
*  Evolving beef export market access requirements for age and source verification: This paper uses costs for different sectors within the beef industry from Brester et. al. 2011. Cow/calf, Dairy, Backgrounding and feedlot, and packer. 
 
These cost estimates include source and age verification participation costs (2009) along with the tags and tagging costs.

COW/CALF: 
Currently Tag Cattle - Annual cost range from $\$14.51$/head (operation with less than 50 head) to $\$2.75$ (operation with more than 5000 head)
Currently not tagging cattle - Annual cost range from $\$15.83$/head (operation with less than 50 head) to $\$5.39$ (operation with more than 5000 head).

DAIRY:
Currently Tag Cattle - Annual cost range from $\$17.34$/head (operation with less than 50 head) to $\$3.83$ (operation with more than 2000 head)
Currently not tagging cattle - Annual cost range from $\$16.79$/head (operation with less than 50 head) to $\$5.02$ (operation with more than 2000 head)

BACKGROUNDING:
Annual cost range from $\$23.51$/head (operation with 31 head) to $\$0.39$ (operation with 2963 head)

FEEDLOT: 
Annual cost range from $\$15.89$/head (< 1000 head) to $\$0.15$ (> 32000 head)

PACKING PLANTS:
Steers and Heifers: Annual cost range from $\$0.47$/head for smallest plants (slightly over 300 head per year) to $\$0.16$/head for the largest plants (approximately 1.3 million head per plant per year).


Just tag and tagging costs: 

COW/CALF: 
Currently Tag Cattle - $\$4.21$/head (<50 head) to $\$2.40$/head (>5000 head)
Currently Not Tagging Cattle - $\$5.54$/head (<50 head) to $\$5.04$/head (>5000 head)

DAIRY:
Currently Tag Cattle - $\$5.57$/head (<50 head) to $\$3.34$/head (>2000 head)
Currently Not Tagging Cattle - $\$5.04$/head (<50 head) to $\$4.55$/head (>5000 head)

BACKGROUNDING:
$\$0.75$/head (31 head) to $\$0.14$/head (2,963 head)

FEEDLOT:
$\$0.50$/head (<1000 head) to $\$0.12$/head (>32000 head)


These five group subtotals are summed to obtain the total cost for the cattle industry of adopting ASV. Costs associated with several sectors within the beef industry are aggregated for use in the economic model. For example, dairy, background, and feedlot costs are aggregated into the slaughter cattle sector while packer costs are referred to as wholesale costs.

For our analysis I am following the same strategy as the study i.e., aggregating all the costs to get a total cost.

Just the tag and tagging costs excluding Dairy sector:

Currently Tag Cattle - Small operations: 4.21 + 0.75 + 0.50 + 0.47= $\$5.93$/head ; 
                       Large operations: 2.40 + 0.14 + 0.12 + 0.16= $\$2.82$/head;
                       Average Cost: $\$4.375$/head
                       
Currently Not Tagging Cattle - Small operations: 5.54 + 0.75 + 0.50 + 0.47= $\$7.26$/head ; 
                               Large operations: 5.04 + 0.14 + 0.12 + 0.16 = $\$5.46$/head;
                               Average Cost: $\$6.36$/head

Total costs (includes SAV costs):

Currently Tag Cattle - Small operations: 14.51 + 23.51 + 15.89 + 0.47 = $\$54.38$/head;
                        Large operations: 2.75 + 0.39 + 0.15 + 0.16 =  $\$3.45$/head;
                        Average Cost: $\$28.91$/head
                        
Currently Not Tagging Cattle - Small operations: 15.83 + 23.51 + 15.89 + 0.47 = $\$55.7$/head ; 
                               Large operations: 5.39 + 0.39 + 0.15 + 0.16 = $\$6.09$/head;
                               Average Cost: $\$30.89$/head




* ANIMAL IDENTIFICATION AND TRACING IN THE UNITED STATES: This paper uses the cost estimates for all the meat sectors from the report Blasi et.al.2009. Similar to the above study, they use cost estimates for different segments within the industry. Specifically, Cow/Calf, Dairy, Background and feedlot, packer, and dairy. These costs are estimated according to the size of the operation. (We have to note that in our model we just look at the cost per pound of beef.)

 ESTIMATED COST (2007) OF RFID FULL TRACEABILITY TECHNOLOGY ADOPTION
 
COW/CALF: 
Operation that Currently Tags Cattle - Annual cost range from $\$5.95$/head (operation with less than 50 head) to $\$2.88$/head (operation with more than 5000 head)

Operation that Currently not tagging cattle - Annual cost range from $\$7.17$/head (<50 head) to $\$5.44$/head (>5000 head)

DAIRY: 
Operation that Currently Tags Cattle - Annual cost range from $\$5.84$/head (operation with less than 50 head) to $\$2.53$/head (operation with more than 5000 head)
Operation that Currently not tagging cattle - Annual cost range from $\$5.28$/head (<50 head) to $\$2.97$/head (>5000 head)

BACKGROUND: 
$\$1.70$/head (31 head) to $\$0.56$/head (2963 head)

FEEDLOT:
$\$1.37$/head (<1000 head) to $\$0.30$/head (>50000)

AUCTION MARKETS:
$\$0.145$ per head and a data storage cost of $\$0.085$ per head totaling $\$0.23$ per head

PACKERS:
steer and heifer: Volume weighted average = $0.15
cow and bull: Volume weighted average = $0.29
calf: Volume weighted average = $0.36

Summary of Cattle Industry Costs Under Scenario #3 (full traceability)
Beef Cow/Calf - $\$4.22$, Dairy- $\$3.43$, Background- $\$0.70$, Feedlot- $\$0.50$, Auction Yards- $\$0.23$, Packers- $\$0.10$,
Industry Total - $\$2.07$. (Should I use these cost numbers?)


Similar to the above study, I am aggregating all the costs to get the total costs

Just the tag and tagging costs excluding Dairy sector:

Currently Tag Cattle - Small operations: 5.95 + 1.7 + 1.37 + 0.23 + 0.1 = $\$9.35$/head ; 
                        Large operations: 2.88 + 0.56 + 0.30 + 0.23 + 0.1 = $\$4.07$/head;
                        Average Cost: $\$6.71$/head
                        
Currently Not Tagging Cattle - Small operations: 7.17 + 1.7 + 1.37 + 0.23 + 0.1 = $\$10.57$/head ; 
                               Large operations: 5.44 + 0.56 + 0.30 + 0.23 + 0.1  = $\$6.63$/head;
                               Average Cost: $\$8.600$/head






How do we include these costs in the model? These costs are dollars per head, our model is dollars per pound of meat. We have to convert these into those units and include in the model. One more question, which costs should we use? AJAE paper published in 2010 (the cost estimates in this paper is taken from "B-C analysis of NAIS" 2009) or Food Policy paper published in 2013 (the cost estimates in this paper is taken from "Economic assessment of evolving red meat export market access requirements for traceability of livestock and meat" 2011)? How about the costs in year? If we are modeling from that year then, we can use the same numbers. For instance, 2007 numbers from B-C analysis of NAIS, 2009 numbers from SAV study.


These studies also have exogenous supply changes. Each of these percentage increases in costs represent upward shifts (reductions in supply) of the respective supply functions. Should we include these in our model?


> prices_predict_co4_merge_1
   Year        ps    ps_hat       pc   pc_hat       hc   hc_hat
1  1995  73.13848  73.13848 39.63831 39.63831 22.22140 22.22140
2  1996  71.94968  71.94968 29.42669 29.42669 21.40059 21.40059
3  1997  68.52043  68.52043 25.13961 25.13961 20.24202 20.24202
4  1998  71.94369  71.94369 30.03167 30.03167 21.42799 21.42799
5  1999  67.26439  67.26439 29.76600 29.76600 20.11536 20.11536
6  2000  66.71444  66.71444 35.67818 35.67818 20.24662 20.24662
7  2001  71.38667  71.38667 39.18025 39.18025 21.71276 21.71276
8  2002  77.45695  77.45695 38.92914 38.92914 23.38696 23.38696
9  2003  71.88787  71.88787 36.10449 36.10449 21.70423 21.70423
10 2004  85.27742  85.27742 42.86109 42.86109 25.74831 25.74831
11 2005  93.84528  93.84528 46.77600 46.77600 28.31645 28.31645
12 2006  98.40325  98.40325 48.16605 48.16605 29.64939 29.64939
13 2007  95.07463  95.07463 44.28933 44.28933 28.53849 28.53849
14 2008  98.09811  98.09811 46.04089 46.04089 29.46253 29.46253
15 2009  97.61380  97.61380 48.19609 48.19609 29.43153 29.43153
16 2010  89.38108  94.13237 41.22256 39.16086 26.80954 28.03036
17 2011  99.07526 102.01824 53.70653 53.63042 30.10236 30.91612
18 2012 118.44584 120.73861 71.01090 71.57372 36.31455 36.97855
19 2013 125.84015 129.59245 79.74475 78.68863 38.78816 39.77993
20 2014 128.14942 130.92201 81.12356 81.08454 39.49589 40.26422

> demand_predict_co4_merge_1
   Year   Demand demand_est       sl   sl_est       cl   cl_est
1  1995 24.83759   24.83759 21.82188 21.82188 2.302060 2.302060
2  1996 26.61096   26.61096 22.20732 22.20732 2.846171 2.846171
3  1997 26.08250   26.08250 21.74065 21.74065 2.904022 2.904022
4  1998 25.36675   25.36675 21.31377 21.31377 2.756853 2.756853
5  1999 25.59906   25.59906 22.10180 22.10180 2.553043 2.553043
6  2000 25.23158   25.23158 22.92858 22.92858 2.342896 2.342896
7  2001 25.29501   25.29501 23.09476 23.09476 2.431552 2.431552
8  2002 25.78781   25.78781 22.45959 22.45959 2.722287 2.722287
9  2003 26.38079   26.38079 23.32932 23.32932 2.653358 2.653358
10 2004 25.65654   25.65654 22.49520 22.49520 3.016005 3.016005
11 2005 25.28962   25.28962 20.87259 20.87259 3.123926 3.123926
12 2006 26.19774   26.19774 21.25707 21.25707 3.437565 3.437565
13 2007 27.22475   27.22475 22.52401 22.52401 3.663189 3.663189
14 2008 27.58232   27.58232 22.78210 22.78210 3.828958 3.828958
15 2009 27.27225   27.27225 22.60927 22.60927 3.573933 3.573933
16 2010 26.72546   27.31957 21.96549 21.96549 3.381468 3.944931
17 2011 26.32405   26.55828 22.54025 22.54025 3.242917 3.472332
18 2012 25.75572   25.90177 22.10291 22.10291 3.332812 3.477040
19 2013 25.63414   26.00131 21.61570 21.61570 3.166676 3.521648
20 2014 24.87055   25.09359 21.19936 21.19936 3.167428 3.385955

> percentChange_price_1
  Year percentChange_ps percentChange_pc percentChange_hc
1 2010         5.315765      -5.00139213         4.553653
2 2011         2.970447      -0.14172264         2.703291
3 2012         1.935710       0.79258667         1.828464
4 2013         2.981797      -1.32437288         2.556872
5 2014         2.163558      -0.04809532         1.945328

> percentChange_demand_1
  Year percentChange_demand percentChange_sl percentChange_cl
1 2010            2.2230005     1.617407e-14        16.663268
2 2011            0.8897844     0.000000e+00         7.074329
3 2012            0.5670303     0.000000e+00         4.327525
4 2013            1.4323597     0.000000e+00        11.209633
5 2014            0.8968260    -1.675859e-14         6.899216

> costsRevenues_1
  Year clRev_diff costSupply_cl slRev_diff costSupply_sl totalRev_diff costSupply_t
1 2010  0.1509412     0.2758409  1.0436437     0.2895184     1.1945849    0.5653593
2 2011  0.1205677     0.2692686  0.6633547     0.2950919     0.7839224    0.5643604
3 2012  0.1219874     0.2714993  0.5067685     0.2833291     0.6287559    0.5548284
4 2013  0.2458794     0.2530752  0.8110854     0.2755595     1.0569647    0.5286347
5 2014  0.1759564     0.2501090  0.5877708     0.2674643     0.7637271    0.5175732








<!-- line 1075 in code -->




